/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atsinformatica.midler.ui;

import br.com.atsinformatica.erp.dao.ListaPedidoDAO;
import br.com.atsinformatica.erp.entity.ListaPedidoERPBean;
import br.com.atsinformatica.midler.components.renderer.DateCellRenderer;
import br.com.atsinformatica.midler.components.renderer.MoneyCellRenderer;
import br.com.atsinformatica.midler.components.renderer.StatusPedidoCellRenderer;
import com.towel.el.annotation.AnnotationResolver;
import com.towel.swing.table.ObjectTableModel;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;
import javax.swing.table.TableColumn;
import org.apache.log4j.Logger;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JMenu;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author GregoryPacheco
 */
public class PanelListaPedidos extends javax.swing.JPanel {

    private AnnotationResolver resolver = new AnnotationResolver(ListaPedidoERPBean.class);
    private String fields = "codPedidoResulth,codPedidoEcom,cliente,valor,status,dataPedido,formaPagamento,horaIntegracao";
    private ObjectTableModel objTableModelListaPedido = new ObjectTableModel(resolver, fields);
    private static Logger logger = Logger.getLogger(PanelListaPedidos.class);
    //Linha da Tabela selecionada, vai ser capturada no evento MousePressed
    private int linhaSelecionada = -1;
//            

    /**
     * Creates new form PanelListaPedidos
     */
    public PanelListaPedidos() {
        initComponents();
        carregarGridListaPedido();
        refleshGrid();
        criandoMenuPopUp();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbListaPedido = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jBfechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jTbListaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        jTbListaPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTbListaPedidoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTbListaPedido);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Listagem de pedidos em aberto");

        jBfechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons/door_out.png"))); // NOI18N
        jBfechar.setText("Fechar");
        jBfechar.setToolTipText("Fechar");
        jBfechar.setFocusable(false);
        jBfechar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBfechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBfechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfecharActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Status");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Forma de pagamento");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Data do pedido");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtragem de pedidos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(12, 12, 12)
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton2)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBfechar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBfechar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBfecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfecharActionPerformed
        //fecha tudo
        this.removeAll();
        //atualiza ui
        this.updateUI();

        setBorder(null);

    }//GEN-LAST:event_jBfecharActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jTbListaPedidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTbListaPedidoMousePressed
        //Seleciona a linha no ponto em que o mouse é clicado
        Point point = evt.getPoint();
        linhaSelecionada = jTbListaPedido.rowAtPoint(point);
        System.out.println("Numero " + linhaSelecionada);
        //jTbListaPedido.setRowSelectionInterval(linhaSelecionada, linhaSelecionada);


    }//GEN-LAST:event_jTbListaPedidoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBfechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbListaPedido;
    // End of variables declaration//GEN-END:variables

    private void carregarGridListaPedido() {
        jTbListaPedido.setModel(objTableModelListaPedido);
        jTbListaPedido.setAutoCreateRowSorter(true);
        objTableModelListaPedido.clear();
        for (int i = 0; i < 19; i++) {
            objTableModelListaPedido.add(null);
        }
        //Fazendo referencia a campo do Grid
        TableColumn colStatus = jTbListaPedido.getColumnModel().getColumn(4);
        TableColumn colDtPedido = jTbListaPedido.getColumnModel().getColumn(5);
        TableColumn colDtIntegracao = jTbListaPedido.getColumnModel().getColumn(7);
        TableColumn colValor = jTbListaPedido.getColumnModel().getColumn(3);

        //Renderizando valores do Grid
        colStatus.setCellRenderer(new StatusPedidoCellRenderer());
        colDtPedido.setCellRenderer(new DateCellRenderer());
        colDtIntegracao.setCellRenderer(new DateCellRenderer());
        colValor.setCellRenderer(new MoneyCellRenderer());

    }

    private void refleshGrid() {
        try {
            objTableModelListaPedido.clear();
            ListaPedidoDAO dao = new ListaPedidoDAO();
            //Lista de Pedidos com Status diferente de Finalizado e Cancelado
            List<ListaPedidoERPBean> listaPedidos = dao.listaTodos();

            if (!listaPedidos.isEmpty()) {
                objTableModelListaPedido.addAll(listaPedidos);
            }

        } catch (Exception e) {
            logger.error("Erro ao caregar lista de pedidos: " + e);
        }
    }

    public void criandoMenuPopUp() {

        //Declarando MenuPopUp
        JPopupMenu popupMenu = new JPopupMenu();

        //Criando itens do menu
        JMenuItem menuItemFinalizarPedido = new JMenuItem("Finalizar Pedido");
        JMenuItem menuItemCancelarPedido = new JMenuItem("Cancelar Pedido");

        //Criando Menu para sub menu de Status
        JMenu menuAtualizarStatusPedido = new JMenu("Atualizar o status do pedido");

        //Criando menu de status
        JMenuItem SubItemAguardandoConfirmacaoPagamento = new JMenuItem("Aguardando confirmação do pagamento");
        JMenuItem subItemNotaFiscal = new JMenuItem("Nota fiscal");
        JMenuItem subItemEnviado = new JMenuItem("Enviado");
        JMenuItem subItemEntregue = new JMenuItem("Entregue");
        JMenuItem subItemCancelado = new JMenuItem("Cancelado");

        //Adicionando o menu no subMenu Status
        menuAtualizarStatusPedido.add(SubItemAguardandoConfirmacaoPagamento);
        menuAtualizarStatusPedido.addSeparator();
        menuAtualizarStatusPedido.add(subItemNotaFiscal);
        menuAtualizarStatusPedido.addSeparator();
        menuAtualizarStatusPedido.add(subItemEnviado);
        menuAtualizarStatusPedido.addSeparator();
        menuAtualizarStatusPedido.add(subItemEntregue);
        menuAtualizarStatusPedido.addSeparator();
        menuAtualizarStatusPedido.add(subItemCancelado);

        //Adicionado o MenuItem no Menu
        popupMenu.add(menuItemFinalizarPedido);
        popupMenu.addSeparator();
        popupMenu.add(menuItemCancelarPedido);
        popupMenu.addSeparator();
        popupMenu.add(menuAtualizarStatusPedido);

        //Adicionando o MenuPopUP na Grid
        jTbListaPedido.setComponentPopupMenu(popupMenu);

        //Crianco ação ao clicar no MenuPopUp (Finalizar Pedido).
        menuItemFinalizarPedido.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                int yes;
                //Confirmação para finalizar o pedido.
                yes = JOptionPane.showConfirmDialog(null, "Deseja finalizar o pedido", "Confirmação", JOptionPane.YES_NO_OPTION);
                if (yes == JOptionPane.YES_OPTION) {
                    //Chamdndo a função que finaliza o pedido
                    finalizarPedido();
                }
            }
        });

        //Crianco ação ao clicar no MenuPopUp (Cancelar Pedido).
        menuItemCancelarPedido.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                int yes;
                //Confirmação para finalizar o pedido.
                yes = JOptionPane.showConfirmDialog(null, "Deseja cancelar o pedido", "Confirmação", JOptionPane.YES_NO_OPTION);
                if (yes == JOptionPane.YES_OPTION) {
                    //Chamdndo a função
                    cancelarPedido();
                }
            }
        });

        //Criando ação ao clicar no SubMenu (Aguardando confirmação do pagamento)
        SubItemAguardandoConfirmacaoPagamento.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Aguardando confirmação do pagamento");

            }
        });

        //Criando ação ao clicar no SubMenu (Nota Fiscal)
        subItemNotaFiscal.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Nota Fiscal");

            }
        });

        //Criando ação ao clicar no SubMenu (Enviado)
        subItemEnviado.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Enviado");

            }
        });

        //Criando ação ao clicar no SubMenu (Entregue)
        subItemEntregue.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Entregue");

            }
        });

        //Criando ação ao clicar no SubMenu (Cancelar)
        subItemCancelado.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Cancelar");

            }
        });

    }

    public void finalizarPedido() {
        try {

            ListaPedidoERPBean listaPedidoERPBean = new ListaPedidoERPBean();
            listaPedidoERPBean.setCodPedidoResulth((int) jTbListaPedido.getValueAt(linhaSelecionada, 0));
            listaPedidoERPBean.setCodPedidoEcom((int) jTbListaPedido.getValueAt(linhaSelecionada, 1));
            listaPedidoERPBean.setDataFinalizacaoPedido(new Date());

            ListaPedidoDAO listaPedidoDAO = new ListaPedidoDAO();
            if (listaPedidoDAO.validacaoFinalizarPedido(listaPedidoERPBean)) {
                if (listaPedidoDAO.finalizarPedido(listaPedidoERPBean)) {
                    JOptionPane.showMessageDialog(null, "Pedido finalizado com sucesso!");
                    //Atualizando Grid
                    refleshGrid();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Esse pedido não pode ser finalizado!");
            }

        } catch (Exception e) {
            logger.error("Erro ao finalizar pedidos: " + e);
        }
    }

    public void cancelarPedido() {
        try {

            ListaPedidoERPBean listaPedidoERPBean = new ListaPedidoERPBean();
            listaPedidoERPBean.setCodPedidoResulth((int) jTbListaPedido.getValueAt(linhaSelecionada, 0));
            listaPedidoERPBean.setCodPedidoEcom((int) jTbListaPedido.getValueAt(linhaSelecionada, 1));
            listaPedidoERPBean.setDataFinalizacaoPedido(new Date());

            ListaPedidoDAO listaPedidoDAO = new ListaPedidoDAO();
            if (listaPedidoDAO.validacaoCancelarPedido(listaPedidoERPBean)) {
                if (listaPedidoDAO.cancelarPedido(listaPedidoERPBean)) {
                    JOptionPane.showMessageDialog(null, "Pedido cancelado com sucesso!");
                    //Atualizando Grid
                    refleshGrid();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Esse pedido não pode ser cancelado!");
            }

        } catch (Exception e) {
            logger.error("Erro ao finalizar pedidos: " + e);
        }
    }
    
    public void statusAguadandoPagamento(){
        try {
            ListaPedidoERPBean listaPedidoERPBean = new ListaPedidoERPBean();
            listaPedidoERPBean.setCodPedidoResulth((int) jTbListaPedido.getValueAt(linhaSelecionada, 0));
            listaPedidoERPBean.setCodPedidoEcom((int) jTbListaPedido.getValueAt(linhaSelecionada, 1));

            ListaPedidoDAO listaPedidoDAO = new ListaPedidoDAO();
            if (listaPedidoDAO.validacaoCancelarPedido(listaPedidoERPBean)) {
                if (listaPedidoDAO.cancelarPedido(listaPedidoERPBean)) {
                    JOptionPane.showMessageDialog(null, "Pedido cancelado com sucesso!");
                    //Atualizando Grid
                    refleshGrid();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Esse pedido não pode ser cancelado!");
            }

        } catch (Exception e) {
            logger.error("Erro ao finalizar pedidos: " + e);
        }
    }

}
